language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 8.0

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1
  fast_finish: true

before_install:
  - composer self-update
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install:
  - composer install --optimize-autoloader --prefer-source

script:
  - vendor/bin/phpunit --verbose
